CREATE TABLE Vertex(
    NAMEVERTEX INTEGER,
    COLOR INTEGER,
    DESCRIPTION VARCHAR(200),
    WEIGHT REAL,
    CONSTRAINT Vertexkey PRIMARY KEY(NAMEVERTEX)
);

CREATE TABLE Edges(
    V1ID INTEGER,
    V2ID INTEGER,
    WEIGHT REAL,
    FLAG1 INTEGER,
    DESCRIPTION VARCHAR(200),
    CONSTRAINT ForeignVertex FOREIGN KEY (V1ID)
        REFERENCES Vertex,
    CONSTRAINT ForeignVertex1 FOREIGN KEY (V2ID)
        REFERENCES Vertex,
    CONSTRAINT Edgeskey PRIMARY KEY (V1ID, V2ID)
);
